theme: jekyll-theme-slate
title: Jeremy Miller
description: Data Scientist
permalink: pretty
plugins:
  - jekyll-relative-links
  - jemoji
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LearningMap.md
